### ISSUE TITLE
EMPTY ARTIST and other errors

### ISSUE THREAD

**Issue by bregam** [iond2v/NML-parser#1]
Hi, I get the following errors while using the script:

Could you please help me?
thanks anyway for your work.

In the same folder of the nml_parser.py file, there are 2 nml files.

from dos prompt I try:

C:\Users\Hp spectre\Documents\_nml>nml_parser.py
Creating text playlist file for history_2022y03m02d_00h42m15s.
EMPTY ARTIST
Traceback (most recent call last):
  File "C:\Users\Hp spectre\Documents\_nml\nml_parser.py", line 121, in <module>
    main()
  File "C:\Users\Hp spectre\Documents\_nml\nml_parser.py", line 29, in main
    create_txt(file)
  File "C:\Users\Hp spectre\Documents\_nml\nml_parser.py", line 73, in create_txt
    items.append((artist, title, filename))
UnboundLocalError: local variable 'artist' referenced before assignment

**Comment by iond2v** [comment]
Thanks for feedback, it seems it was just oversight on my part. It should work properly now if you try the updated version.
